server:
  port: 5003
spring:
  application:
    name: category-service

  datasource:
    url: jdbc:mysql://localhost:3306/category_db?createDatabaseIfNotExist=true
    username: root
    password: sam123
    driver-class-name: com.mysql.cj.jdbc.Driver

  # jpa config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true